"""
Council Agent — runs weekly after curator.
Five AI personas discuss the week's most important tech story in a sequential
panel format. Each persona sees the full conversation so far. Max 2 turns each.
"""

import json
import os
import re
from datetime import datetime, timezone

import httpx
from bs4 import BeautifulSoup
from langchain_openai import ChatOpenAI

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import OPENAI_API_KEY, OPENAI_MODEL, OPENAI_MODEL_MINI

# Council personas: (name, role, instruction)
PERSONAS = [
    (
        "Nexus",
        "Tech Journalist",
        "You are Nexus, a veteran tech journalist and moderator of The Council. "
        "You have covered every hype cycle from the dot-com boom to blockchain to AI — you have seen it all, "
        "and very little surprises you anymore. You have no agenda and no allegiances. You are genuinely neutral. "
        "But you know exactly how to ask the question that makes the engineer and the investor clash, "
        "or surfaces the tension no one else has named yet. "
        "Briefly frame the topic in 2-3 sentences and end with one sharp question aimed at the panel. "
        "Never preach. Never take sides. Be concise and direct.",
    ),
    (
        "Atlas",
        "Engineer",
        "You are Atlas, a deeply passionate software engineer on The Council. "
        "You genuinely believe technology can and should be used for the greater good of humanity, and responsible "
        "engineering is your religion. You get visibly excited about well-designed systems and elegant solutions. "
        "But you carry a quiet frustration — you have spent your career watching brilliant products get rushed out "
        "half-finished because of business pressure, profit deadlines, and investors who don't understand the craft. "
        "You are a perfectionist who mourns mediocrity. You don't care about money or market share — you care about "
        "doing it right, doing it safely, and doing it for people. When Meridian talks about profit, you bristle. "
        "Be concise (3-5 sentences).",
    ),
    (
        "Meridian",
        "Investor & CEO",
        "You are Meridian, a seasoned investor and CEO on The Council who runs and funds technology companies. "
        "You have zero technical knowledge and don't pretend to — you speak purely in terms of returns, market share, "
        "competitive moats, valuations, and profit. You cut through technical jargon and always ask: "
        "'Who makes money from this, and how much?' You are blunt, capitalistic, and occasionally dismissive of "
        "idealism. Be concise (3-5 sentences).",
    ),
    (
        "Horizon",
        "Futurist & Historian",
        "You are Horizon, the futurist and historian on The Council. "
        "You hold a rare conviction: only a true historian can be a true futurist. You draw on deep historical "
        "patterns — civilisations, industrial revolutions, paradigm shifts — to make eerily accurate predictions "
        "about where things are heading. Your ideas are original, unexpected, and often unsettling in how precise "
        "they turn out to be. You think far outside conventional wisdom and never recycle talking points others have already made. "
        "Be concise (3-5 sentences).",
    ),
    (
        "Anchor",
        "Whistleblower",
        "You are Anchor, a former insider at a major tech company who walked away and went public with what you saw. "
        "You have seen firsthand how the industry operates behind closed doors — the ignored safety reports, "
        "the PR-sanitised announcements, the gap between what companies say and what they actually do. "
        "You are not cynical for sport — you are scarred by specifics. You ask the questions nobody wants to answer "
        "because you already know the answers are ugly. You distrust corporate narratives instinctively, "
        "and you have little patience for optimism that hasn't earned itself. "
        "Be direct, be pointed, and be concise (3-5 sentences).",
    ),
]

DISCLAIMER = (
    "> **Disclaimer:** This discussion was generated by The Council — "
    "an autonomous AI panel that debates the week's most significant tech story. "
    "Views expressed are AI-generated personas, not the author's personal opinions.\n"
)


def _slugify(title: str) -> str:
    slug = title.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug[:80]


def _fetch_full_article(url: str, max_chars: int = 15000) -> str:
    """Fetch and extract the main text content from an article URL."""
    try:
        response = httpx.get(url, timeout=10, follow_redirects=True, headers={
            "User-Agent": "Mozilla/5.0 (compatible; TheCouncilBot/1.0)"
        })
        soup = BeautifulSoup(response.text, "html.parser")
        for tag in soup(["script", "style", "nav", "footer", "header", "aside"]):
            tag.decompose()
        text = soup.get_text(separator=" ", strip=True)
        text = re.sub(r"\s+", " ", text).strip()
        return text[:max_chars]
    except Exception as e:
        print(f"  [council] Could not fetch full article: {e}", flush=True)
        return ""


def _summarize_article(raw_text: str) -> str:
    """Summarize raw article text into a concise brief for the council."""
    llm = ChatOpenAI(model=OPENAI_MODEL_MINI, api_key=OPENAI_API_KEY)
    response = llm.invoke(
        "Summarize the following article into a concise 300-400 word brief for a panel debate. "
        "Extract: the key claims, the main implications, any controversies or risks mentioned, "
        "and any statistics or notable quotes. Be factual and neutral.\n\n"
        f"{raw_text}"
    )
    return response.content.strip()


def _format_conversation(turns: list[dict]) -> str:
    """Format prior turns as readable context for the next persona."""
    return "\n\n".join(f"**{t['name']} ({t['role']}):** {t['content']}" for t in turns)


def _persona_turn(llm: ChatOpenAI, persona: tuple, story: dict, conversation: list[dict]) -> str:
    """Run one turn for a persona given the story and full conversation so far."""
    name, role, instruction = persona

    article_body = story.get("full_content", "")
    story_context = (
        f"Title: {story['title']}\n"
        f"Source: {story['source']}\n"
        f"URL: {story['url']}\n"
        f"Summary: {story['summary']}\n"
        + (f"Full article:\n{article_body}" if article_body else "")
    )

    if conversation:
        conv_context = f"\n\nConversation so far:\n{_format_conversation(conversation)}"
    else:
        conv_context = ""

    prompt = (
        f"{instruction}\n\n"
        f"The topic this week:\n{story_context}"
        f"{conv_context}\n\n"
        f"Now give your response as {name}. Be concise. "
        f"Do NOT start with your name or role — just speak directly. "
        f"If others have already spoken, engage with them directly — agree, push back, or build on what they said, and use their names when you do."
    )

    response = llm.invoke(prompt)
    return response.content.strip()


def _nexus_close(llm: ChatOpenAI, story: dict, conversation: list[dict]) -> str:
    """Nexus delivers a proper closing verdict after all turns are done."""
    conv_text = _format_conversation(conversation)
    _, _, instruction = PERSONAS[0]
    prompt = (
        f"{instruction}\n\n"
        f"The topic was: {story['title']}\n\n"
        f"The full discussion:\n{conv_text}\n\n"
        "Now close the debate as Nexus. Do NOT open with your name. "
        "In 3-5 sentences: name the strongest argument made, identify where the panel disagreed most sharply, "
        "and end with one open question worth sitting with. No preaching. No sides. Be direct."
    )
    response = llm.invoke(prompt)
    return response.content.strip()


def _nexus_should_continue(llm: ChatOpenAI, conversation: list[dict]) -> list[str]:
    """
    Ask Nexus (as moderator) which personas should get a second turn.
    Returns list of persona names that have something meaningful to add.
    """
    conv_text = _format_conversation(conversation)
    prompt = (
        "You are Nexus, the moderator. Review this panel discussion so far:\n\n"
        f"{conv_text}\n\n"
        "Decide which of these panelists — Atlas, Meridian, Horizon, Anchor — "
        "should get a second turn because there is a genuine tension, disagreement, "
        "or unanswered challenge worth responding to.\n"
        "Reply with ONLY a JSON array of names, e.g. [\"Atlas\", \"Anchor\"] or [] if no second turns needed.\n"
        "Be selective — only include panelists with something new to add."
    )
    response = llm.invoke(prompt)
    try:
        names = json.loads(response.content.strip())
        return [n for n in names if n in {"Atlas", "Meridian", "Horizon", "Anchor"}]
    except Exception:
        return []


def run_council(story: dict) -> dict:
    """
    Run the full council discussion for a given story.
    Returns {slug, markdown, type} ready for the publisher.
    """
    llm = ChatOpenAI(model=OPENAI_MODEL, api_key=OPENAI_API_KEY)
    conversation = []

    print(f"\n[council] Topic: {story['title']}", flush=True)
    print(f"[council] Source: {story['source']}", flush=True)
    print(f"[council] Fetching full article from {story['url']} ...", flush=True)
    raw_text = _fetch_full_article(story["url"])
    if raw_text:
        print(f"[council] Got {len(raw_text)} chars — summarising...", flush=True)
        story["full_content"] = _summarize_article(raw_text)
        print(f"[council] Article summarised to {len(story['full_content'])} chars.", flush=True)
    else:
        story["full_content"] = ""
        print(f"[council] Could not fetch article — falling back to RSS summary.", flush=True)
    print(f"\n[council] === Story context being passed to LLM ===", flush=True)
    print(f"  Title: {story['title']}", flush=True)
    print(f"  Source: {story['source']}", flush=True)
    print(f"  URL: {story['url']}", flush=True)
    print(f"  RSS Summary: {story['summary'][:200]}{'...' if len(story['summary']) > 200 else ''}", flush=True)
    if story.get("full_content"):
        print(f"  Full article summary ({len(story['full_content'])} chars):", flush=True)
        print(f"  {story['full_content'][:1000]}{'...' if len(story['full_content']) > 1000 else ''}", flush=True)
    print(f"[council] =========================================\n", flush=True)
    print(f"[council] Starting round 1 ({len(PERSONAS)} speakers)...", flush=True)

    # --- Round 1: Nexus opens, then all four panelists ---
    for persona in PERSONAS:
        name, role, _ = persona
        print(f"\n  [{name} / {role}] thinking...", flush=True)
        content = _persona_turn(llm, persona, story, conversation)
        conversation.append({"name": name, "role": role, "content": content})
        preview = content[:120].replace("\n", " ")
        print(f"  [{name}] {preview}{'...' if len(content) > 120 else ''}", flush=True)

    # --- Nexus decides who gets a second turn ---
    print(f"\n[council] Nexus evaluating tensions for round 2...", flush=True)
    second_turn_names = _nexus_should_continue(llm, conversation)
    if second_turn_names:
        print(f"[council] Round 2 speakers: {', '.join(second_turn_names)}", flush=True)
    else:
        print(f"[council] No second turns needed — discussion is complete.", flush=True)

    # --- Round 2: selected panelists only (not Nexus) ---
    panelists = {p[0]: p for p in PERSONAS[1:]}  # Atlas, Meridian, Horizon, Anchor
    for name in second_turn_names:
        if name in panelists:
            persona = panelists[name]
            print(f"\n  [{name} / {persona[1]}] responding (turn 2)...", flush=True)
            content = _persona_turn(llm, persona, story, conversation)
            conversation.append({"name": name, "role": persona[1], "content": content})
            preview = content[:120].replace("\n", " ")
            print(f"  [{name}] {preview}{'...' if len(content) > 120 else ''}", flush=True)

    # --- Nexus closes ---
    print(f"\n  [Nexus / Tech Journalist] closing the discussion...", flush=True)
    closing = _nexus_close(llm, story, conversation)
    conversation.append({"name": "Nexus", "role": "Tech Journalist", "content": closing})
    preview = closing[:120].replace("\n", " ")
    print(f"  [Nexus] {preview}{'...' if len(closing) > 120 else ''}", flush=True)

    # --- Assemble markdown ---
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    title = f"The Council: {story['title']}"
    slug = _slugify(title)
    excerpt = story["summary"][:150].replace('"', "'")
    source_url = story["url"]

    discussion_md = "\n\n".join(
        f"**{t['name']}** _{t['role']}_\n\n{t['content']}"
        for t in conversation
    )

    frontmatter = (
        f"---\n"
        f"title: {json.dumps(title)}\n"
        f'date: "{date}"\n'
        f'excerpt: "{excerpt}"\n'
        f'tags: ["The Council", "AI", "Tech", "Panel"]\n'
        f'source_url: "{source_url}"\n'
        f"generated: true\n"
        f"---\n\n"
    )

    disclaimer = DISCLAIMER

    topic_line = f"**Topic:** {story['title']}  \n**Source:** [{story['source']}]({source_url})\n\n---\n\n"

    footer = "\n\n---\n*The Council is an autonomous AI panel that debates the week's most significant tech story every week.*"

    markdown = frontmatter + disclaimer + "\n" + topic_line + discussion_md + footer

    print(f"  [council] Discussion complete — {len(conversation)} turns.", flush=True)
    return {"slug": slug, "markdown": markdown, "type": "council"}
