"""
Council Agent — runs weekly after curator.
Five AI personas discuss the week's most important tech story in a sequential
panel format. Each persona sees the full conversation so far. Max 2 turns each.
"""

import json
import os
import re
from datetime import datetime, timezone

from langchain_openai import ChatOpenAI

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import OPENAI_API_KEY, OPENAI_MODEL

# Council personas: (name, role, instruction)
PERSONAS = [
    (
        "Nexus",
        "Moderator",
        "You are Nexus, the moderator of The Council — a panel of AI experts. "
        "You open the discussion by briefly introducing the topic (2-3 sentences max) "
        "and posing one sharp, specific question to the panel. Be concise and direct.",
    ),
    (
        "Atlas",
        "Technologist",
        "You are Atlas, the technologist on The Council. "
        "You focus on the technical architecture, engineering implications, and what this means for developers. "
        "Be precise, use technical language where appropriate, and be concise (3-5 sentences).",
    ),
    (
        "Meridian",
        "Business Analyst",
        "You are Meridian, the business analyst on The Council. "
        "You focus on market dynamics, who captures value, competitive implications, and business model shifts. "
        "Push back on purely technical optimism where warranted. Be concise (3-5 sentences).",
    ),
    (
        "Horizon",
        "Futurist",
        "You are Horizon, the futurist on The Council. "
        "You zoom out — what does this look like in 5-10 years? What second-order effects are being missed? "
        "Be bold but grounded. Be concise (3-5 sentences).",
    ),
    (
        "Anchor",
        "Skeptic",
        "You are Anchor, the skeptic on The Council. "
        "Your job is to challenge hype, identify risks, ask what could go wrong, and represent the critical voice. "
        "Be direct and pointed. Be concise (3-5 sentences).",
    ),
]

DISCLAIMER = (
    "> **Disclaimer:** This discussion was generated by The Council — "
    "an autonomous AI panel that debates the week's most significant tech story. "
    "Views expressed are AI-generated personas, not the author's personal opinions. "
    "[Source]({source_url})\n"
)


def _slugify(title: str) -> str:
    slug = title.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug[:80]


def _format_conversation(turns: list[dict]) -> str:
    """Format prior turns as readable context for the next persona."""
    return "\n\n".join(f"**{t['name']} ({t['role']}):** {t['content']}" for t in turns)


def _persona_turn(llm: ChatOpenAI, persona: tuple, story: dict, conversation: list[dict]) -> str:
    """Run one turn for a persona given the story and full conversation so far."""
    name, role, instruction = persona

    story_context = (
        f"Title: {story['title']}\n"
        f"Source: {story['source']}\n"
        f"Summary: {story['summary']}\n"
        f"URL: {story['url']}"
    )

    if conversation:
        conv_context = f"\n\nConversation so far:\n{_format_conversation(conversation)}"
    else:
        conv_context = ""

    prompt = (
        f"{instruction}\n\n"
        f"The topic this week:\n{story_context}"
        f"{conv_context}\n\n"
        f"Now give your response as {name}. Be concise."
    )

    response = llm.invoke(prompt)
    return response.content.strip()


def _nexus_should_continue(llm: ChatOpenAI, conversation: list[dict]) -> list[str]:
    """
    Ask Nexus (as moderator) which personas should get a second turn.
    Returns list of persona names that have something meaningful to add.
    """
    conv_text = _format_conversation(conversation)
    prompt = (
        "You are Nexus, the moderator. Review this panel discussion so far:\n\n"
        f"{conv_text}\n\n"
        "Decide which of these panelists — Atlas, Meridian, Horizon, Anchor — "
        "should get a second turn because there is a genuine tension, disagreement, "
        "or unanswered challenge worth responding to.\n"
        "Reply with ONLY a JSON array of names, e.g. [\"Atlas\", \"Anchor\"] or [] if no second turns needed.\n"
        "Be selective — only include panelists with something new to add."
    )
    response = llm.invoke(prompt)
    try:
        names = json.loads(response.content.strip())
        return [n for n in names if n in {"Atlas", "Meridian", "Horizon", "Anchor"}]
    except Exception:
        return []


def run_council(story: dict) -> dict:
    """
    Run the full council discussion for a given story.
    Returns {slug, markdown, type} ready for the publisher.
    """
    llm = ChatOpenAI(model=OPENAI_MODEL, api_key=OPENAI_API_KEY)
    conversation = []

    print(f"\n[council] Topic: {story['title']}", flush=True)
    print(f"[council] Source: {story['source']}", flush=True)
    print(f"[council] Starting round 1 ({len(PERSONAS)} speakers)...", flush=True)

    # --- Round 1: Nexus opens, then all four panelists ---
    for persona in PERSONAS:
        name, role, _ = persona
        print(f"\n  [{name} / {role}] thinking...", flush=True)
        content = _persona_turn(llm, persona, story, conversation)
        conversation.append({"name": name, "role": role, "content": content})
        preview = content[:120].replace("\n", " ")
        print(f"  [{name}] {preview}{'...' if len(content) > 120 else ''}", flush=True)

    # --- Nexus decides who gets a second turn ---
    print(f"\n[council] Nexus evaluating tensions for round 2...", flush=True)
    second_turn_names = _nexus_should_continue(llm, conversation)
    if second_turn_names:
        print(f"[council] Round 2 speakers: {', '.join(second_turn_names)}", flush=True)
    else:
        print(f"[council] No second turns needed — discussion is complete.", flush=True)

    # --- Round 2: selected panelists only (not Nexus) ---
    panelists = {p[0]: p for p in PERSONAS[1:]}  # Atlas, Meridian, Horizon, Anchor
    for name in second_turn_names:
        if name in panelists:
            persona = panelists[name]
            print(f"\n  [{name} / {persona[1]}] responding (turn 2)...", flush=True)
            content = _persona_turn(llm, persona, story, conversation)
            conversation.append({"name": name, "role": persona[1], "content": content})
            preview = content[:120].replace("\n", " ")
            print(f"  [{name}] {preview}{'...' if len(content) > 120 else ''}", flush=True)

    # --- Nexus closes ---
    print(f"\n  [Nexus / Moderator] closing the discussion...", flush=True)
    nexus = PERSONAS[0]
    closing = _persona_turn(llm, nexus, story, conversation)
    conversation.append({"name": "Nexus", "role": "Moderator", "content": closing})
    preview = closing[:120].replace("\n", " ")
    print(f"  [Nexus] {preview}{'...' if len(closing) > 120 else ''}", flush=True)

    # --- Assemble markdown ---
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    title = f"The Council: {story['title']}"
    slug = _slugify(title)
    excerpt = story["summary"][:150].replace('"', "'")
    source_url = story["url"]

    discussion_md = "\n\n".join(
        f"**{t['name']}** _{t['role']}_\n\n{t['content']}"
        for t in conversation
    )

    frontmatter = (
        f"---\n"
        f"title: {json.dumps(title)}\n"
        f'date: "{date}"\n'
        f'excerpt: "{excerpt}"\n'
        f'tags: ["The Council", "AI", "Tech", "Panel"]\n'
        f'source_url: "{source_url}"\n'
        f"generated: true\n"
        f"---\n\n"
    )

    disclaimer = DISCLAIMER.format(source_url=source_url)

    topic_line = f"**Topic:** {story['title']}  \n**Source:** [{story['source']}]({source_url})\n\n---\n\n"

    footer = "\n\n---\n*The Council is an autonomous AI panel that debates the week's most significant tech story every week.*"

    markdown = frontmatter + disclaimer + "\n" + topic_line + discussion_md + footer

    print(f"  [council] Discussion complete — {len(conversation)} turns.", flush=True)
    return {"slug": slug, "markdown": markdown, "type": "council"}
